Fix type checking errors (#67)
* TS2339: Property 'length' does not exist on type 'unknown'.

* TS2339: Property 'map' does not exist on type 'unknown'.

* TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string'.

* TypeError: Cannot read property 'type' of undefined

* TypeError: Cannot read property 'isOfCategory' of undefined

* PR fix: clarify marker collection meanings

* Handle marker category is array

Co-authored-by: KJoslyn <KJoslyn29@gmail.com>